site_name: CV LaTeX Class
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Available Sections: sections.md
  - Customization: customization.md
  - Examples: examples.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
