name: Release on Tag
on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Create Versioned Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get tag name
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Prepare release files
        run: |
          mkdir release
          cp cv.cls release/
          cp -r images release/
          zip -r cv-${{ steps.get_tag.outputs.tag }}.zip release
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_tag.outputs.tag }}
          tag_name: ${{ steps.get_tag.outputs.tag }}
          files: cv-${{ steps.get_tag.outputs.tag }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
